"""Base BoQItemOutput schema + registry-builder used by all 70 TechSpec templates.

Single-file registry pattern (vs 70 individual files) for maintainability:
  - One Python module to read when debugging
  - All schemas share the same BoQItemOutput surface
  - Per-discipline customisation via TechSpecTemplate.extra_required_fields + validators
"""
from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field, field_validator


# ─── Universal BoQ item output schema ────────────────────────────────


class BoQItemOutput(BaseModel):
    """Structured output enforced via Vertex AI response_schema / instructor.

    Every BoQ line item generated by the drafter conforms to this shape.
    """
    model_config = ConfigDict(extra="forbid")

    sno: int = Field(..., ge=1, description="Sequential number within the BoQ")
    item_name: str = Field(..., min_length=10, description="Short item name shown in S.No column header")
    spec_text: str = Field(
        ..., min_length=150, max_length=4000,
        description="Multi-paragraph technical specification. Must reference applicable IS/EN/IEC/ASHRAE/UL/EUROVENT standards by name+number.",
    )
    work_type: str = Field(..., description="e.g. HVAC WORKS, ELECTRICAL WORKS, FIRE FIGHTING WORKS, ROAD WORKS")
    short_desc: str = Field(..., max_length=80, description="Compact tag e.g. AHU, HRW, HT_SWITCHGEAR")
    apss_cl_no: str = Field(..., description="AP Schedule of Rates clause; use 'NON SOR / KD A 1.x' for non-standard items")
    est_qty: float = Field(..., ge=0, description="Estimated quantity at this scale")
    uom: str = Field(..., description="Unit of measurement (Nos / Cum / m / m² / kg / MT / RM / lump sum)")
    rate_inr: float = Field(..., ge=0, description="Project-scaled unit rate in INR")
    citations: list[str] = Field(default_factory=list, description="IS/EN/IEC/ASHRAE/UL/EUROVENT standards cited in spec_text")

    @field_validator("citations")
    @classmethod
    def _dedupe_citations(cls, v: list[str]) -> list[str]:
        return sorted(set(v))


# ─── TechSpec template definition ────────────────────────────────────


class TechSpecTemplate(BaseModel):
    """A discipline-specific generator template.

    Each entry encodes:
      - retrieval_query_template: BGE-M3 query string format with {placeholders}
      - llm_prompt_template: Vertex AI prompt with {placeholders}
      - expected_citations: standards typically referenced for items in this category
      - llm_model: which Vertex model to use (gemini_flash / gemini_pro / sonnet_46)
      - expected_output_tokens: budget signal
      - typical_uom: default unit
      - sample_short_descs: example items in this discipline (improves few-shot prompting)
    """
    model_config = ConfigDict(extra="forbid")

    template_id: str                                  # e.g. "mep/hvac/ahu"
    discipline: str                                   # "MEP" / "Civil"
    sub_discipline: str                               # "HVAC" / "Roads"
    item_category: str                                # "AHU" / "Pavement_Bituminous"
    work_type_label: str                              # for BoQ work_type column
    typical_uom: str
    typical_short_desc: str
    sample_short_descs: list[str] = Field(default_factory=list)
    expected_citations: list[str] = Field(default_factory=list)
    retrieval_query_template: str
    llm_prompt_template: str
    validation_rules: list[str] = Field(default_factory=list)
    llm_model: str = "gemini_flash"                   # default cheap; pro for complex PCC
    expected_output_tokens: int = 350


# ─── Registry definitions ────────────────────────────────────────────


_DEFAULT_PROMPT_HEAD = """You are drafting a Bill of Quantities (BoQ) line item for an AP Capital Projects tender.

PROJECT CONTEXT:
  Tender: {tender_subject}
  Estimated Contract Value: ₹{ecv_inr_words} (₹{ecv_inr:,})
  Discipline: {discipline} / {sub_discipline}
  Period of completion: {period_months} months
  Form of contract: {form_of_contract}

ITEM TO DRAFT:
  S.No: {sno}
  Item name from skeleton: {item_name}
  Estimated quantity: {est_qty} {uom}

REFERENCE EXAMPLES (from comparable AP Capital projects):
{retrieved_examples}

INSTRUCTIONS:
1. Write a detailed technical specification of 200-400 words for this item.
2. Reference applicable {expected_standards} standards explicitly by code + number.
3. Cover construction (materials, dimensions, tolerances), performance class, compliance,
   installation/testing requirements.
4. Match the depth + tone of the reference examples above.
5. Output as structured JSON matching the BoQItemOutput schema.
"""


def _build_template(
    *,
    discipline: str,
    sub_discipline: str,
    item_category: str,
    work_type_label: str,
    typical_uom: str,
    typical_short_desc: str,
    sample_descs: list[str],
    expected_citations: list[str],
    retrieval_extra: str = "",
    llm_model: str = "gemini_flash",
    expected_output_tokens: int = 350,
) -> TechSpecTemplate:
    template_id = f"{discipline.lower()}/{sub_discipline.lower()}/{item_category.lower()}".replace(" ", "_")

    retrieval_query = (
        f"{sub_discipline} {item_category} {{item_name}} {{uom}} "
        f"{' '.join(expected_citations[:4])} {retrieval_extra}"
    ).strip()

    llm_prompt = _DEFAULT_PROMPT_HEAD.replace(
        "{discipline}", discipline
    ).replace(
        "{sub_discipline}", sub_discipline
    ).replace(
        "{expected_standards}", " / ".join(expected_citations[:5]) if expected_citations else "applicable IS/EN/IEC"
    )

    validation_rules = [
        "spec_text length 150-4000 chars",
        f"work_type matches '{work_type_label}'",
        "at least 1 citation when expected_citations is non-empty" if expected_citations else "citations optional for commodity items",
    ]

    return TechSpecTemplate(
        template_id=template_id,
        discipline=discipline,
        sub_discipline=sub_discipline,
        item_category=item_category,
        work_type_label=work_type_label,
        typical_uom=typical_uom,
        typical_short_desc=typical_short_desc,
        sample_short_descs=sample_descs,
        expected_citations=expected_citations,
        retrieval_query_template=retrieval_query,
        llm_prompt_template=llm_prompt,
        validation_rules=validation_rules,
        llm_model=llm_model,
        expected_output_tokens=expected_output_tokens,
    )


# ─── REGISTRY: 37 MEP + 35 Civil templates ───────────────────────────


REGISTRY: dict[str, TechSpecTemplate] = {}


def _r(t: TechSpecTemplate) -> None:
    REGISTRY[t.template_id] = t


# === MEP: ELECTRICAL (7) ===
_r(_build_template(
    discipline="MEP", sub_discipline="Electrical", item_category="HT_Switchgear",
    work_type_label="ELECTRICAL WORKS", typical_uom="Nos", typical_short_desc="HT-SG",
    sample_descs=["HT_SWITCHGEAR_11KV", "HT_SWITCHGEAR_33KV"],
    expected_citations=["IS 13118", "IEC 62271", "IS 11171", "IEC 60694"],
    expected_output_tokens=400,
))
_r(_build_template(
    discipline="MEP", sub_discipline="Electrical", item_category="Transformer",
    work_type_label="ELECTRICAL WORKS", typical_uom="Nos", typical_short_desc="TX",
    sample_descs=["TRANSFORMER_2500KVA", "TRANSFORMER_1600KVA"],
    expected_citations=["IS 2026", "IS 1180", "IEC 60076"],
    expected_output_tokens=400,
))
_r(_build_template(
    discipline="MEP", sub_discipline="Electrical", item_category="LT_Panel",
    work_type_label="ELECTRICAL WORKS", typical_uom="Nos", typical_short_desc="LT-PANEL",
    sample_descs=["LT_MCC_3200A", "PCC_PANEL_1600A", "APFC_PANEL"],
    expected_citations=["IS 8623", "IEC 61439", "IS 13947"],
))
_r(_build_template(
    discipline="MEP", sub_discipline="Electrical", item_category="Cable_XLPE",
    work_type_label="ELECTRICAL WORKS", typical_uom="RM", typical_short_desc="HT-CABLE",
    sample_descs=["XLPE_11KV_3CX300", "XLPE_LT_3CX240"],
    expected_citations=["IS 7098", "IS 1554", "IS 8130"],
))
_r(_build_template(
    discipline="MEP", sub_discipline="Electrical", item_category="Lighting",
    work_type_label="ELECTRICAL WORKS", typical_uom="Nos", typical_short_desc="LED",
    sample_descs=["LED_PANEL_30W", "LED_STREET_120W"],
    expected_citations=["IS 10322", "IS 16104"],
))
_r(_build_template(
    discipline="MEP", sub_discipline="Electrical", item_category="Earthing",
    work_type_label="ELECTRICAL WORKS", typical_uom="set", typical_short_desc="EARTH",
    sample_descs=["EARTHING_PIT_3M", "EARTH_STRIP_25X3"],
    expected_citations=["IS 3043", "IS 5216"],
))
_r(_build_template(
    discipline="MEP", sub_discipline="Electrical", item_category="UPS",
    work_type_label="ELECTRICAL WORKS", typical_uom="Nos", typical_short_desc="UPS",
    sample_descs=["UPS_520KVA", "UPS_120KVA"],
    expected_citations=["IS 14257", "IEC 62040"],
))


# === MEP: HVAC (10) ===
_r(_build_template(
    discipline="MEP", sub_discipline="HVAC", item_category="AHU",
    work_type_label="HVAC WORKS", typical_uom="Nos", typical_short_desc="AHU",
    sample_descs=["AHU_4000CFM", "AHU_8000CFM_DOUBLE_SKIN"],
    expected_citations=["EN 1886", "EUROVENT", "ASHRAE 52.2", "EN 779", "UL 1995", "UL 2043", "MERV 8", "MERV 14"],
    expected_output_tokens=500,
))
_r(_build_template(
    discipline="MEP", sub_discipline="HVAC", item_category="Chiller",
    work_type_label="HVAC WORKS", typical_uom="Nos", typical_short_desc="CHILLER",
    sample_descs=["WATER_COOLED_CHILLER_500TR", "AIR_COOLED_CHILLER_300TR"],
    expected_citations=["AHRI 550/590", "ASHRAE 90.1", "ISO 9001"],
    expected_output_tokens=500,
))
_r(_build_template(
    discipline="MEP", sub_discipline="HVAC", item_category="CoolingTower",
    work_type_label="HVAC WORKS", typical_uom="Nos", typical_short_desc="CT",
    sample_descs=["CT_500TR_CROSSFLOW"],
    expected_citations=["CTI ATC-105", "IS 13169"],
))
_r(_build_template(
    discipline="MEP", sub_discipline="HVAC", item_category="Ducting",
    work_type_label="HVAC WORKS", typical_uom="kg", typical_short_desc="GI-DUCT",
    sample_descs=["GI_DUCTING_24G", "GI_DUCTING_22G_INSULATED"],
    expected_citations=["SMACNA", "IS 277", "IS 655"],
))
_r(_build_template(
    discipline="MEP", sub_discipline="HVAC", item_category="BMS",
    work_type_label="HVAC WORKS", typical_uom="lump sum", typical_short_desc="BMS",
    sample_descs=["BMS_DDC_PANELS", "BMS_SOFTWARE"],
    expected_citations=["ASHRAE 135 (BACnet)", "ISO 16484"],
    llm_model="gemini_pro",
    expected_output_tokens=600,
))
_r(_build_template(
    discipline="MEP", sub_discipline="HVAC", item_category="RefrigerantPiping",
    work_type_label="HVAC WORKS", typical_uom="RM", typical_short_desc="REF-PIPE",
    sample_descs=["COPPER_REFRIGERANT_PIPE_5/8"],
    expected_citations=["IS 1239", "ASTM B280", "ASME B31.5"],
))
_r(_build_template(
    discipline="MEP", sub_discipline="HVAC", item_category="VAV",
    work_type_label="HVAC WORKS", typical_uom="Nos", typical_short_desc="VAV",
    sample_descs=["VAV_BOX_PRESSURE_INDEPENDENT"],
    expected_citations=["ARI 880"],
))
_r(_build_template(
    discipline="MEP", sub_discipline="HVAC", item_category="FCU",
    work_type_label="HVAC WORKS", typical_uom="Nos", typical_short_desc="FCU",
    sample_descs=["FCU_2_PIPE_400CFM"],
    expected_citations=["ARI 440", "EUROVENT"],
))
_r(_build_template(
    discipline="MEP", sub_discipline="HVAC", item_category="Pumps",
    work_type_label="HVAC WORKS", typical_uom="Nos", typical_short_desc="CHWP",
    sample_descs=["CHILLED_WATER_PUMP_PRIMARY", "CONDENSER_WATER_PUMP"],
    expected_citations=["ISO 9906", "API 610"],
))
_r(_build_template(
    discipline="MEP", sub_discipline="HVAC", item_category="Controls",
    work_type_label="HVAC WORKS", typical_uom="set", typical_short_desc="HVAC-CTRL",
    sample_descs=["DDC_CONTROLLER_AHU"],
    expected_citations=["ASHRAE 135"],
))


# === MEP: FIRE (8) ===
_r(_build_template(
    discipline="MEP", sub_discipline="Fire", item_category="SprinklerSystem",
    work_type_label="FIRE FIGHTING WORKS", typical_uom="Nos", typical_short_desc="SPRINKLER",
    sample_descs=["UPRIGHT_SPRINKLER_15MM", "PENDENT_SPRINKLER"],
    expected_citations=["NFPA 13", "IS 15105", "UL FM"],
))
_r(_build_template(
    discipline="MEP", sub_discipline="Fire", item_category="Hydrant",
    work_type_label="FIRE FIGHTING WORKS", typical_uom="Nos", typical_short_desc="HYDRANT",
    sample_descs=["INTERNAL_HYDRANT_VALVE_63MM", "EXTERNAL_HYDRANT"],
    expected_citations=["IS 884", "IS 5290", "NBC 2016"],
))
_r(_build_template(
    discipline="MEP", sub_discipline="Fire", item_category="FirePump",
    work_type_label="FIRE FIGHTING WORKS", typical_uom="Nos", typical_short_desc="FIRE-PUMP",
    sample_descs=["ELECTRIC_FIRE_PUMP_2280LPM", "DIESEL_FIRE_PUMP_2280LPM"],
    expected_citations=["NFPA 20", "IS 12469"],
))
_r(_build_template(
    discipline="MEP", sub_discipline="Fire", item_category="AlarmPanel",
    work_type_label="FIRE FIGHTING WORKS", typical_uom="Nos", typical_short_desc="FACP",
    sample_descs=["FACP_ADDRESSABLE_2_LOOP", "FACP_CONVENTIONAL_8_ZONE"],
    expected_citations=["NFPA 72", "UL 864", "EN 54"],
))
_r(_build_template(
    discipline="MEP", sub_discipline="Fire", item_category="SmokeDetector",
    work_type_label="FIRE FIGHTING WORKS", typical_uom="Nos", typical_short_desc="DETECTOR",
    sample_descs=["PHOTOELECTRIC_SMOKE_DETECTOR", "MULTI_SENSOR_DETECTOR"],
    expected_citations=["EN 54-7", "UL 268"],
))
_r(_build_template(
    discipline="MEP", sub_discipline="Fire", item_category="FireExtinguisher",
    work_type_label="FIRE FIGHTING WORKS", typical_uom="Nos", typical_short_desc="EXTINGUISHER",
    sample_descs=["ABC_DCP_6KG", "CO2_4_5KG", "CLEAN_AGENT_2KG"],
    expected_citations=["IS 15683", "IS 13849"],
))
_r(_build_template(
    discipline="MEP", sub_discipline="Fire", item_category="Suppression",
    work_type_label="FIRE FIGHTING WORKS", typical_uom="set", typical_short_desc="SUPPRESSION",
    sample_descs=["FM200_SUPPRESSION_50KG", "NOVEC_1230_SUPPRESSION"],
    expected_citations=["NFPA 2001", "ISO 14520"],
))
_r(_build_template(
    discipline="MEP", sub_discipline="Fire", item_category="GasSystem",
    work_type_label="FIRE FIGHTING WORKS", typical_uom="set", typical_short_desc="VESDA",
    sample_descs=["VESDA_ASPIRATING_DETECTOR"],
    expected_citations=["EN 54-20", "UL 268"],
))


# === MEP: LIFTS (3) ===
_r(_build_template(
    discipline="MEP", sub_discipline="Lifts", item_category="PassengerLift",
    work_type_label="LIFTS", typical_uom="Nos", typical_short_desc="PAX-LIFT",
    sample_descs=["MRL_PAX_LIFT_24P_2.5MPS", "MRL_PAX_LIFT_24P_4MPS"],
    expected_citations=["IS 14665", "EN 81-20", "EN 81-50"],
))
_r(_build_template(
    discipline="MEP", sub_discipline="Lifts", item_category="ServiceLift",
    work_type_label="LIFTS", typical_uom="Nos", typical_short_desc="SVC-LIFT",
    sample_descs=["SERVICE_LIFT_1000KG_1MPS"],
    expected_citations=["IS 14665", "EN 81-20"],
))
_r(_build_template(
    discipline="MEP", sub_discipline="Lifts", item_category="FreightLift",
    work_type_label="LIFTS", typical_uom="Nos", typical_short_desc="GOODS-LIFT",
    sample_descs=["GOODS_LIFT_2000KG_0.5MPS"],
    expected_citations=["IS 14665"],
))


# === MEP: PLUMBING (6) ===
_r(_build_template(
    discipline="MEP", sub_discipline="Plumbing", item_category="WaterSupply",
    work_type_label="PLUMBING WORKS", typical_uom="RM", typical_short_desc="GI-PIPE",
    sample_descs=["GI_PIPE_25MM_C", "CPVC_PIPE_25MM"],
    expected_citations=["IS 1239", "IS 3589", "ASTM F441"],
))
_r(_build_template(
    discipline="MEP", sub_discipline="Plumbing", item_category="Drainage",
    work_type_label="PLUMBING WORKS", typical_uom="RM", typical_short_desc="SOIL-PIPE",
    sample_descs=["UPVC_SOIL_PIPE_110MM", "CI_SOIL_PIPE_100MM"],
    expected_citations=["IS 13592", "IS 1729"],
))
_r(_build_template(
    discipline="MEP", sub_discipline="Plumbing", item_category="HotWater",
    work_type_label="PLUMBING WORKS", typical_uom="Nos", typical_short_desc="HOT-WTR",
    sample_descs=["COMMERCIAL_GEYSER_100L", "HEAT_PUMP_500L"],
    expected_citations=["IS 2082"],
))
_r(_build_template(
    discipline="MEP", sub_discipline="Plumbing", item_category="Valves",
    work_type_label="PLUMBING WORKS", typical_uom="Nos", typical_short_desc="BV",
    sample_descs=["BUTTERFLY_VALVE_150MM", "GATE_VALVE_100MM"],
    expected_citations=["IS 13095", "BS EN 593"],
))
_r(_build_template(
    discipline="MEP", sub_discipline="Plumbing", item_category="Pumps",
    work_type_label="PLUMBING WORKS", typical_uom="Nos", typical_short_desc="HYDRO-PUMP",
    sample_descs=["HYDROPNEUMATIC_PUMP_5HP", "BOOSTER_PUMP_2HP"],
    expected_citations=["ISO 9906"],
))
_r(_build_template(
    discipline="MEP", sub_discipline="Plumbing", item_category="SanitaryFixtures",
    work_type_label="PLUMBING WORKS", typical_uom="Nos", typical_short_desc="WC",
    sample_descs=["WC_FLOOR_MOUNTED", "WASHBASIN_WALL_HUNG", "URINAL_SENSOR"],
    expected_citations=["IS 2556", "IS 774"],
))


# === MEP: MISC (3) ===
_r(_build_template(
    discipline="MEP", sub_discipline="PA", item_category="PA_System",
    work_type_label="PA SYSTEM", typical_uom="set", typical_short_desc="PA",
    sample_descs=["PA_AMPLIFIER_500W", "CEILING_SPEAKER_6W"],
    expected_citations=["IEC 60849", "EN 54-16"],
))
_r(_build_template(
    discipline="MEP", sub_discipline="BMS", item_category="BMS_Integration",
    work_type_label="BMS WORKS", typical_uom="set", typical_short_desc="BMS-INT",
    sample_descs=["BMS_BACNET_GATEWAY"],
    expected_citations=["ASHRAE 135 (BACnet)", "ISO 16484"],
    llm_model="gemini_pro",
    expected_output_tokens=500,
))
_r(_build_template(
    discipline="MEP", sub_discipline="HSD", item_category="HSD_System",
    work_type_label="HSD WORKS", typical_uom="set", typical_short_desc="HSD",
    sample_descs=["DIESEL_STORAGE_TANK_5KL"],
    expected_citations=["IS 803", "OISD"],
))


# === CIVIL: ROADS (8) ===
_r(_build_template(
    discipline="Civil", sub_discipline="Roads", item_category="Bituminous",
    work_type_label="ROAD WORKS", typical_uom="Cum", typical_short_desc="BC-DBM",
    sample_descs=["BITUMINOUS_CONCRETE_30MM", "DENSE_BITUMINOUS_MACADAM_50MM"],
    expected_citations=["MoRTH 500", "IRC SP-53", "IS 73"],
    expected_output_tokens=400,
))
_r(_build_template(
    discipline="Civil", sub_discipline="Roads", item_category="ConcretePavement",
    work_type_label="ROAD WORKS", typical_uom="Cum", typical_short_desc="PQC-M40",
    sample_descs=["PQC_M40_200MM", "RIGID_PAVEMENT_RCC_M40"],
    expected_citations=["IRC 58", "IRC 15", "IS 456"],
    expected_output_tokens=400,
))
_r(_build_template(
    discipline="Civil", sub_discipline="Roads", item_category="BaseCourse",
    work_type_label="ROAD WORKS", typical_uom="Cum", typical_short_desc="WMM",
    sample_descs=["WET_MIX_MACADAM_250MM", "GSB_180MM"],
    expected_citations=["MoRTH 400", "IRC 37"],
))
_r(_build_template(
    discipline="Civil", sub_discipline="Roads", item_category="Subgrade",
    work_type_label="ROAD WORKS", typical_uom="Cum", typical_short_desc="SUBGRADE",
    sample_descs=["SUBGRADE_500MM_COMPACTION_97PCT"],
    expected_citations=["MoRTH 300", "IS 2720"],
))
_r(_build_template(
    discipline="Civil", sub_discipline="Roads", item_category="Kerbs",
    work_type_label="ROAD WORKS", typical_uom="RM", typical_short_desc="KERB",
    sample_descs=["RCC_PRECAST_KERB_500MM"],
    expected_citations=["IRC 86"],
))
_r(_build_template(
    discipline="Civil", sub_discipline="Roads", item_category="Footpaths",
    work_type_label="ROAD WORKS", typical_uom="m²", typical_short_desc="FOOTPATH",
    sample_descs=["PAVER_TILES_25MM"],
    expected_citations=["IS 15658"],
))
_r(_build_template(
    discipline="Civil", sub_discipline="Roads", item_category="RoadMarkings",
    work_type_label="ROAD WORKS", typical_uom="m²", typical_short_desc="MARKING",
    sample_descs=["THERMOPLASTIC_LANE_MARKING"],
    expected_citations=["IS 164", "IRC 35"],
))
_r(_build_template(
    discipline="Civil", sub_discipline="Roads", item_category="Signage",
    work_type_label="ROAD WORKS", typical_uom="m²", typical_short_desc="SIGN",
    sample_descs=["RETROREFLECTIVE_SIGN_BOARD_HIP"],
    expected_citations=["IRC 67", "IS 12899"],
))


# === CIVIL: BRIDGES (5) ===
_r(_build_template(
    discipline="Civil", sub_discipline="Bridges", item_category="Foundation",
    work_type_label="BRIDGE WORKS", typical_uom="RM", typical_short_desc="PILE",
    sample_descs=["BORED_CIS_PILE_1200MM_M30"],
    expected_citations=["IRC 78", "IS 2911"],
    expected_output_tokens=450,
))
_r(_build_template(
    discipline="Civil", sub_discipline="Bridges", item_category="Abutment",
    work_type_label="BRIDGE WORKS", typical_uom="Cum", typical_short_desc="ABUTMENT",
    sample_descs=["RCC_M30_ABUTMENT"],
    expected_citations=["IRC 78", "IS 456"],
))
_r(_build_template(
    discipline="Civil", sub_discipline="Bridges", item_category="Pier",
    work_type_label="BRIDGE WORKS", typical_uom="Cum", typical_short_desc="PIER",
    sample_descs=["RCC_M30_PIER"],
    expected_citations=["IRC 21", "IS 456"],
))
_r(_build_template(
    discipline="Civil", sub_discipline="Bridges", item_category="Deck",
    work_type_label="BRIDGE WORKS", typical_uom="Cum", typical_short_desc="DECK",
    sample_descs=["PSC_BOX_GIRDER_M40"],
    expected_citations=["IRC 18", "IS 1343"],
    llm_model="gemini_pro",
    expected_output_tokens=500,
))
_r(_build_template(
    discipline="Civil", sub_discipline="Bridges", item_category="Bearings",
    work_type_label="BRIDGE WORKS", typical_uom="Nos", typical_short_desc="POT-BRG",
    sample_descs=["POT_PTFE_BEARING"],
    expected_citations=["IRC 83"],
))


# === CIVIL: DRAINS (4) ===
_r(_build_template(
    discipline="Civil", sub_discipline="Drains", item_category="Stormwater",
    work_type_label="DRAIN WORKS", typical_uom="RM", typical_short_desc="STORM-DRAIN",
    sample_descs=["RCC_M30_STORM_DRAIN_0.6X0.6", "RCC_M30_STORM_DRAIN_1.5X2.0"],
    expected_citations=["IRC SP-50", "CPHEEO Storm Water Manual"],
))
_r(_build_template(
    discipline="Civil", sub_discipline="Drains", item_category="RCC_Box",
    work_type_label="DRAIN WORKS", typical_uom="RM", typical_short_desc="RCC-BOX",
    sample_descs=["RCC_BOX_DRAIN_1X1_M30"],
    expected_citations=["IS 456", "IRC 6"],
))
_r(_build_template(
    discipline="Civil", sub_discipline="Drains", item_category="KerbDrain",
    work_type_label="DRAIN WORKS", typical_uom="RM", typical_short_desc="KERB-DRAIN",
    sample_descs=["RCC_KERB_DRAIN_300MM"],
    expected_citations=["IRC 86"],
))
_r(_build_template(
    discipline="Civil", sub_discipline="Drains", item_category="Manhole",
    work_type_label="DRAIN WORKS", typical_uom="Nos", typical_short_desc="MH",
    sample_descs=["RCC_INSPECTION_MANHOLE_900MM", "RCC_DROP_MANHOLE_1200MM"],
    expected_citations=["IS 4127", "CPHEEO"],
))


# === CIVIL: SEWERAGE (6) ===
_r(_build_template(
    discipline="Civil", sub_discipline="Sewerage", item_category="GravityMain",
    work_type_label="SEWERAGE WORKS", typical_uom="RM", typical_short_desc="SEWER-MAIN",
    sample_descs=["DWC_PE_SN8_400MM", "RCC_NP3_600MM"],
    expected_citations=["IS 16098", "IS 458", "CPHEEO Sewerage Manual"],
))
_r(_build_template(
    discipline="Civil", sub_discipline="Sewerage", item_category="Manhole",
    work_type_label="SEWERAGE WORKS", typical_uom="Nos", typical_short_desc="SEWER-MH",
    sample_descs=["RCC_SEWER_MANHOLE_1200MM_TYPE_C"],
    expected_citations=["IS 4127", "CPHEEO"],
))
_r(_build_template(
    discipline="Civil", sub_discipline="Sewerage", item_category="PumpingStation",
    work_type_label="SEWERAGE WORKS", typical_uom="set", typical_short_desc="IPS",
    sample_descs=["INTERMEDIATE_PUMPING_STATION_SEWAGE"],
    expected_citations=["CPHEEO", "IS 5120"],
    llm_model="gemini_pro",
    expected_output_tokens=550,
))
_r(_build_template(
    discipline="Civil", sub_discipline="Sewerage", item_category="ForceMain",
    work_type_label="SEWERAGE WORKS", typical_uom="RM", typical_short_desc="FORCE-MAIN",
    sample_descs=["DI_K7_FORCE_MAIN_400MM"],
    expected_citations=["IS 8329"],
))
_r(_build_template(
    discipline="Civil", sub_discipline="Sewerage", item_category="TreatmentSkid",
    work_type_label="SEWERAGE WORKS", typical_uom="set", typical_short_desc="STP",
    sample_descs=["STP_PACKAGED_500KLD"],
    expected_citations=["CPHEEO", "CPCB Discharge Norms"],
    llm_model="gemini_pro",
    expected_output_tokens=600,
))
_r(_build_template(
    discipline="Civil", sub_discipline="Sewerage", item_category="VentPipe",
    work_type_label="SEWERAGE WORKS", typical_uom="RM", typical_short_desc="VENT",
    sample_descs=["CI_VENT_STACK_100MM"],
    expected_citations=["IS 1729"],
))


# === CIVIL: WATER (4) ===
_r(_build_template(
    discipline="Civil", sub_discipline="WaterSupply", item_category="DistributionMain",
    work_type_label="WATER SUPPLY WORKS", typical_uom="RM", typical_short_desc="DI-K7",
    sample_descs=["DI_K7_WATER_MAIN_300MM", "DI_K7_WATER_MAIN_500MM"],
    expected_citations=["IS 8329", "CPHEEO Water Supply Manual"],
))
_r(_build_template(
    discipline="Civil", sub_discipline="WaterSupply", item_category="OHSR",
    work_type_label="WATER SUPPLY WORKS", typical_uom="Nos", typical_short_desc="OHSR",
    sample_descs=["RCC_OHSR_500KL_25M_STAGING"],
    expected_citations=["IS 11682", "IS 3370"],
    expected_output_tokens=450,
))
_r(_build_template(
    discipline="Civil", sub_discipline="WaterSupply", item_category="GLSR",
    work_type_label="WATER SUPPLY WORKS", typical_uom="Nos", typical_short_desc="GLSR",
    sample_descs=["RCC_GROUND_LEVEL_RESERVOIR_2000KL"],
    expected_citations=["IS 3370", "IS 11682"],
))
_r(_build_template(
    discipline="Civil", sub_discipline="WaterSupply", item_category="Valves",
    work_type_label="WATER SUPPLY WORKS", typical_uom="Nos", typical_short_desc="SLUICE",
    sample_descs=["SLUICE_VALVE_300MM", "BUTTERFLY_VALVE_500MM"],
    expected_citations=["IS 14846", "IS 13095"],
))


# === CIVIL: REUSE (3) ===
_r(_build_template(
    discipline="Civil", sub_discipline="Reuse", item_category="TreatedWaterPipe",
    work_type_label="REUSE WATER WORKS", typical_uom="RM", typical_short_desc="REUSE-DI",
    sample_descs=["DI_K7_REUSE_PIPE_100MM", "HDPE_REUSE_PIPE_75MM"],
    expected_citations=["IS 8329", "IS 14333"],
))
_r(_build_template(
    discipline="Civil", sub_discipline="Reuse", item_category="IrrigationNetwork",
    work_type_label="REUSE WATER WORKS", typical_uom="RM", typical_short_desc="IRR-PIPE",
    sample_descs=["HDPE_IRRIGATION_50MM"],
    expected_citations=["IS 14333"],
))
_r(_build_template(
    discipline="Civil", sub_discipline="Reuse", item_category="Storage",
    work_type_label="REUSE WATER WORKS", typical_uom="Nos", typical_short_desc="REUSE-RES",
    sample_descs=["RCC_REUSE_RESERVOIR_200KL"],
    expected_citations=["IS 3370"],
))


# === CIVIL: POWER+ICT DUCTS (3) ===
_r(_build_template(
    discipline="Civil", sub_discipline="UtilityDucts", item_category="CableDuct",
    work_type_label="UTILITY DUCT WORKS", typical_uom="RM", typical_short_desc="HDPE-DUCT",
    sample_descs=["HDPE_SILICON_COATED_DUCT_160MM", "HDPE_DUCT_225MM"],
    expected_citations=["IS 14930", "IEC 61386"],
))
_r(_build_template(
    discipline="Civil", sub_discipline="UtilityDucts", item_category="ManholePit",
    work_type_label="UTILITY DUCT WORKS", typical_uom="Nos", typical_short_desc="DUCT-MH",
    sample_descs=["RCC_MANHOLE_CABLE_PIT_1.2X1.2"],
    expected_citations=["IS 4127"],
))
_r(_build_template(
    discipline="Civil", sub_discipline="UtilityDucts", item_category="DrawPit",
    work_type_label="UTILITY DUCT WORKS", typical_uom="Nos", typical_short_desc="DRAW-PIT",
    sample_descs=["DRAW_PIT_CABLE_HDPE"],
    expected_citations=[],
))


# === CIVIL: PLANTATION (2) ===
_r(_build_template(
    discipline="Civil", sub_discipline="Plantation", item_category="AvenueTrees",
    work_type_label="PLANTATION WORKS", typical_uom="Nos", typical_short_desc="TREE",
    sample_descs=["AVENUE_TREE_3M_HEIGHT_25L_BAG"],
    expected_citations=["IS 5121"],
))
_r(_build_template(
    discipline="Civil", sub_discipline="Plantation", item_category="SoilTreatment",
    work_type_label="PLANTATION WORKS", typical_uom="m³", typical_short_desc="SOIL-TREAT",
    sample_descs=["TREATED_GARDEN_SOIL_MIX"],
    expected_citations=[],
))


# ─── Public helpers ──────────────────────────────────────────────────


def get_template(template_id: str) -> Optional[TechSpecTemplate]:
    return REGISTRY.get(template_id)


def all_templates() -> list[TechSpecTemplate]:
    return list(REGISTRY.values())
