"""M4.5 Drafter — DOC_REVIEW (documentation re-submission request).

Reads EligibilityMatrix WHERE aggregate_verdict=MARK_FOR_DOCUMENTATION_REVIEW.
Bidder-facing. Bilingual EN+TE.
"""
from __future__ import annotations

import datetime as _dt
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO))

from scripts.m4_drafters._common import (  # noqa: E402
    ARTIFACT_DIR, rest_get_range, rest_post, get_bidder_profile,
    get_tender_info, compute_audit_id, delete_prior_communications,
    snapshot_sentinels, assert_sentinel_preserved,
)


COMMUNICATION_TYPE = "DOC_REVIEW"
SOURCE_REF = "module4:draft_doc_review_request_v1"
SENDER_ROLE = "SYSTEM"


def fetch_findings_by_ids(finding_ids: list[str]) -> list[dict]:
    if not finding_ids:
        return []
    or_clause = ",".join(f"node_id.eq.{fid}" for fid in finding_ids)
    return rest_get_range("kg_nodes", {"select": "node_id,properties",
                                       "or": f"({or_clause})"})


def compose_content_en(profile: dict, tender_info: dict, em_props: dict,
                       gap_findings: list[dict], em_node_id: str) -> str:
    bidder_name = profile.get("company_name", "Bidder")
    today = _dt.date.today().isoformat()
    lines = []
    lines.append(f"# Documentation Re-Submission Request — Tender {tender_info['nit_no']}")
    lines.append("")
    lines.append(f"**Date:** {today}")
    lines.append(f"**To:** {bidder_name}")
    lines.append(f"  {profile.get('communication_address', '(address on file)')}")
    lines.append(f"  Attention: {profile.get('authorized_signatory_name', 'Authorised Signatory')}")
    lines.append("")
    lines.append(f"**Tender:** {tender_info['name']}")
    lines.append(f"**NIT No.:** {tender_info['nit_no']}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("Dear Sir/Madam,")
    lines.append("")
    lines.append(
        f"Review of your bid for the captioned tender indicates that **{len(gap_findings)} "
        f"criteria** require additional documentation before the bid can be conclusively "
        f"evaluated. Your bid has NOT been disqualified; it is held pending re-submission "
        f"of the documentation listed below.")
    lines.append("")
    lines.append("### Documentation required")
    lines.append("")
    for i, f in enumerate(gap_findings, 1):
        fp = f.get("properties") or {}
        lines.append(f"{i}. **{fp.get('typology_code', '?')}** — rule `{fp.get('rule_id', '?')}`")
        lines.append(f"   - Reason: {fp.get('decision_reason', '?')}")
        lines.append(f"   - Statement reference: per AP Standard Tender Document corresponding "
                     f"to the typology above (e.g. Statement VI for Key Personnel, "
                     f"Statement V for Equipment register, etc.)")
        lines.append("")
    lines.append("### Submission window")
    lines.append("")
    lines.append(
        "Please submit the required documentation **within 7 calendar days** of receipt "
        "of this letter, addressed to the Procurement Authority. Submissions must be:")
    lines.append("")
    lines.append("- Signed by the authorised signatory of record (per Form-12)")
    lines.append("- Self-attested if photocopy; original supporting documents available for inspection")
    lines.append("- Referenced to the specific finding number above for committee correlation")
    lines.append("")
    lines.append("### Consequences of non-submission")
    lines.append("")
    lines.append(
        "Failure to submit within 7 days will result in your bid being moved to "
        "**INELIGIBLE** status per AP standard tender norms. Your EMD will be refunded "
        "per the standard EMD return procedure subsequent to disqualification.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("**Yours faithfully,**")
    lines.append("")
    lines.append("Procurement Authority")
    lines.append("(Communication generated by SYSTEM)")
    lines.append("")
    lines.append("**Drilldown reference:**")
    lines.append("")
    lines.append(f"- EligibilityMatrix node_id: `{em_node_id}`")
    lines.append(f"- {len(gap_findings)} GAP_INSUFFICIENT_DATA findings cited above")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    print("=" * 76); print(f"  M4.5 Drafter — {COMMUNICATION_TYPE}"); print("=" * 76)
    sentinel_pre = snapshot_sentinels()
    delete_prior_communications(COMMUNICATION_TYPE, SOURCE_REF)

    rows = rest_get_range("kg_nodes", {
        "select": "node_id,properties",
        "node_type": "eq.EligibilityMatrix",
        "properties->>aggregate_verdict": "eq.MARK_FOR_DOCUMENTATION_REVIEW",
    })
    print(f"  {len(rows)} MARK_FOR_DOC EligibilityMatrix rows")
    n_emitted = 0
    for em in rows:
        ep = em["properties"] or {}
        bidder_id = ep.get("bidder_profile_id"); tender_id = ep.get("tender_id")
        if not (bidder_id and tender_id):
            continue
        fids = ep.get("finding_node_ids") or []
        all_findings = fetch_findings_by_ids(fids)
        gap_findings = [
            f for f in all_findings
            if (f.get("properties") or {}).get("verdict") == "GAP_INSUFFICIENT_DATA"
        ]
        profile = (get_bidder_profile(bidder_id) or {}).get("properties") or {}
        tinfo = get_tender_info(tender_id)
        source_ids = [f["node_id"] for f in gap_findings] + [em["node_id"]]
        audit_id = compute_audit_id(COMMUNICATION_TYPE, bidder_id, tender_id, source_ids)
        content_en = compose_content_en(profile, tinfo, ep, gap_findings, em["node_id"])

        bkey = bidder_id.replace("bid_synth_profile_", "")
        tkey = tender_id.replace("tender_synth_", "")
        artifact = ARTIFACT_DIR / f"{COMMUNICATION_TYPE}_{bkey}_{tkey}.md"
        artifact.write_text(content_en, encoding="utf-8")

        rest_post("kg_nodes", [{
            "doc_id": tender_id, "node_type": "Communication",
            "label": f"DOC_REVIEW — {profile.get('company_name','?')[:40]} × {tinfo['name'][:30]}",
            "properties": {
                "communication_type": COMMUNICATION_TYPE,
                "recipient_bidder_profile_id": bidder_id,
                "recipient_email": profile.get("email_primary"), "recipient_role": None,
                "tender_id": tender_id, "sender_role": SENDER_ROLE,
                "channel": "EMAIL", "language": "EN", "status": "DRAFT",
                "audit_id": audit_id, "source_finding_node_ids": source_ids,
                "content_en": content_en, "content_te": None,
                "artifact_path_md": str(artifact),
                "artifact_path_docx": None, "artifact_path_pdf": None,
                "extracted_by": SOURCE_REF, "defeated": False,
                "n_gap_findings": len(gap_findings),
                "n_source_findings": len(source_ids),
                "bidder_name": profile.get("company_name"),
                "tender_name": tinfo["name"], "tender_nit_no": tinfo["nit_no"],
            },
            "source_ref": SOURCE_REF,
        }])
        n_emitted += 1
        print(f"  ✓ {bkey:5s} × {tkey:8s}  {len(gap_findings)} GAP  audit={audit_id}")

    sentinel_post = snapshot_sentinels()
    assert_sentinel_preserved(sentinel_pre, sentinel_post)
    print(f"\n✓ {COMMUNICATION_TYPE}: {n_emitted} emitted; sentinel preserved")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
