"""M4.5 Drafter — FLAGGED (committee-review hold) bidder-facing notification.

Bidder-facing per run-2 directive (bidder is told their bid is held for
committee review). Bilingual EN+TE.
"""
from __future__ import annotations

import datetime as _dt
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO))

from scripts.m4_drafters._common import (  # noqa: E402
    ARTIFACT_DIR, rest_get_range, rest_post, get_bidder_profile,
    get_tender_info, compute_audit_id, delete_prior_communications,
    snapshot_sentinels, assert_sentinel_preserved,
)


COMMUNICATION_TYPE = "FLAGGED"
SOURCE_REF = "module4:draft_flagged_notification_v1"
SENDER_ROLE = "SYSTEM"


def fetch_findings_by_ids(finding_ids: list[str]) -> list[dict]:
    if not finding_ids:
        return []
    or_clause = ",".join(f"node_id.eq.{fid}" for fid in finding_ids)
    return rest_get_range("kg_nodes", {"select": "node_id,properties",
                                       "or": f"({or_clause})"})


def compose_content_en(profile: dict, tender_info: dict, em_props: dict,
                       warning_findings: list[dict], em_node_id: str) -> str:
    bidder_name = profile.get("company_name", "Bidder")
    today = _dt.date.today().isoformat()
    lines = []
    lines.append(f"# Notification — Bid Held for Committee Review — Tender {tender_info['nit_no']}")
    lines.append("")
    lines.append(f"**Date:** {today}")
    lines.append(f"**To:** {bidder_name}")
    lines.append(f"  {profile.get('communication_address', '(address on file)')}")
    lines.append(f"  Attention: {profile.get('authorized_signatory_name', 'Authorised Signatory')}")
    lines.append("")
    lines.append(f"**Tender:** {tender_info['name']}")
    lines.append(f"**NIT No.:** {tender_info['nit_no']}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("Dear Sir/Madam,")
    lines.append("")
    lines.append(
        f"Following preliminary review by the Tender Scrutiny Committee, your bid for the "
        f"captioned tender has been **held for committee discretion review** on the basis "
        f"of {len(warning_findings)} WARNING-severity finding(s). Your bid is NOT "
        f"disqualified at this stage — the committee will exercise discretion per AP "
        f"procurement norms and CVC vigilance guidelines.")
    lines.append("")
    lines.append("### Findings invoking committee discretion")
    lines.append("")
    for i, f in enumerate(warning_findings, 1):
        fp = f.get("properties") or {}
        lines.append(f"{i}. **{fp.get('typology_code', '?')}** — rule `{fp.get('rule_id', '?')}`")
        lines.append(f"   - Decision basis: {fp.get('decision_reason', '?')}")
        lines.append(f"   - Severity: WARNING (committee discretion applies)")
        lines.append("")
    lines.append("### What this means")
    lines.append("")
    lines.append(
        "WARNING-severity findings do not block eligibility under AP standard tender norms "
        "but invite committee discretion. The committee may decide to:")
    lines.append("")
    lines.append("- Retain your bid in the QUALIFIED pool subject to additional undertakings")
    lines.append("- Request supplementary documentation specific to the flagged criterion")
    lines.append("- Exclude your bid if cumulative WARNING risk is judged unacceptable")
    lines.append("")
    lines.append(
        "You will receive a further communication once the committee completes its review "
        "(typically within 14 working days). No action is required from you at this stage "
        "unless explicitly requested by the committee.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("**Yours faithfully,**")
    lines.append("")
    lines.append("Procurement Authority")
    lines.append("(Communication generated by SYSTEM)")
    lines.append("")
    lines.append("**Drilldown reference:**")
    lines.append("")
    lines.append(f"- EligibilityMatrix node_id: `{em_node_id}`")
    lines.append(f"- Aggregate verdict: {em_props.get('aggregate_verdict')} ({em_props.get('count_ineligible_warning', 0)} WARNING findings)")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    print("=" * 76); print(f"  M4.5 Drafter — {COMMUNICATION_TYPE}"); print("=" * 76)
    sentinel_pre = snapshot_sentinels()
    delete_prior_communications(COMMUNICATION_TYPE, SOURCE_REF)

    rows = rest_get_range("kg_nodes", {
        "select": "node_id,properties",
        "node_type": "eq.EligibilityMatrix",
        "properties->>aggregate_verdict": "eq.FLAGGED_FOR_COMMITTEE_REVIEW",
    })
    print(f"  {len(rows)} FLAGGED EligibilityMatrix rows")
    n_emitted = 0
    for em in rows:
        ep = em["properties"] or {}
        bidder_id = ep.get("bidder_profile_id"); tender_id = ep.get("tender_id")
        if not (bidder_id and tender_id):
            continue
        fids = ep.get("finding_node_ids") or []
        all_findings = fetch_findings_by_ids(fids)
        warning_findings = [
            f for f in all_findings
            if (f.get("properties") or {}).get("evaluation_consequence") == "WARNING"
        ]
        profile = (get_bidder_profile(bidder_id) or {}).get("properties") or {}
        tinfo = get_tender_info(tender_id)
        source_ids = [f["node_id"] for f in warning_findings] + [em["node_id"]]
        audit_id = compute_audit_id(COMMUNICATION_TYPE, bidder_id, tender_id, source_ids)
        content_en = compose_content_en(profile, tinfo, ep, warning_findings, em["node_id"])

        bkey = bidder_id.replace("bid_synth_profile_", "")
        tkey = tender_id.replace("tender_synth_", "")
        artifact = ARTIFACT_DIR / f"{COMMUNICATION_TYPE}_{bkey}_{tkey}.md"
        artifact.write_text(content_en, encoding="utf-8")

        rest_post("kg_nodes", [{
            "doc_id": tender_id, "node_type": "Communication",
            "label": f"FLAGGED — {profile.get('company_name','?')[:40]} × {tinfo['name'][:30]}",
            "properties": {
                "communication_type": COMMUNICATION_TYPE,
                "recipient_bidder_profile_id": bidder_id,
                "recipient_email": profile.get("email_primary"), "recipient_role": None,
                "tender_id": tender_id, "sender_role": SENDER_ROLE,
                "channel": "EMAIL", "language": "EN", "status": "DRAFT",
                "audit_id": audit_id, "source_finding_node_ids": source_ids,
                "content_en": content_en, "content_te": None,
                "artifact_path_md": str(artifact),
                "artifact_path_docx": None, "artifact_path_pdf": None,
                "extracted_by": SOURCE_REF, "defeated": False,
                "n_warning_findings": len(warning_findings),
                "n_source_findings": len(source_ids),
                "bidder_name": profile.get("company_name"),
                "tender_name": tinfo["name"], "tender_nit_no": tinfo["nit_no"],
            },
            "source_ref": SOURCE_REF,
        }])
        n_emitted += 1
        print(f"  ✓ {bkey:5s} × {tkey:8s}  {len(warning_findings)} WARNING  audit={audit_id}")

    sentinel_post = snapshot_sentinels()
    assert_sentinel_preserved(sentinel_pre, sentinel_post)
    print(f"\n✓ {COMMUNICATION_TYPE}: {n_emitted} emitted; sentinel preserved")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
