"""M4.5 Drafter — BID_ACK (bid receipt acknowledgement) per BidSubmission.

Emits 1 Communication per BidSubmission (27 in current corpus).
Bidder-facing; translatable to Telugu via batch step.
"""
from __future__ import annotations

import datetime as _dt
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO))

from scripts.m4_drafters._common import (  # noqa: E402
    ARTIFACT_DIR, rest_get_range, rest_post, get_bidder_profile,
    get_tender_info, compute_audit_id, delete_prior_communications,
    snapshot_sentinels, assert_sentinel_preserved,
)


COMMUNICATION_TYPE = "BID_ACK"
SOURCE_REF = "module4:draft_bid_acknowledgment_v1"
SENDER_ROLE = "SYSTEM"


def fetch_supplementaries_for_bid(doc_id: str) -> dict:
    """Returns {'LetterOfBid': props, 'EMD_BG': props, 'PricedBoQ': props}."""
    out = {}
    for nt in ("LetterOfBid", "EMD_BG", "PricedBoQ"):
        rows = rest_get_range("kg_nodes", {
            "select": "node_id,properties",
            "doc_id": f"eq.{doc_id}",
            "node_type": f"eq.{nt}",
        })
        if rows:
            out[nt] = {"node_id": rows[0]["node_id"], "props": rows[0]["properties"] or {}}
    return out


def compose_content_en(profile: dict, tender_info: dict, bid_sub: dict,
                       supps: dict) -> str:
    bidder_name = profile.get("company_name", "Bidder")
    today = _dt.date.today().isoformat()
    lob = supps.get("LetterOfBid", {}).get("props", {})
    emd = supps.get("EMD_BG", {}).get("props", {})
    boq = supps.get("PricedBoQ", {}).get("props", {})

    lines = []
    lines.append(f"# Bid Receipt Acknowledgement — Tender {tender_info['nit_no']}")
    lines.append("")
    lines.append(f"**Date:** {today}")
    lines.append(f"**To:** {bidder_name}")
    lines.append(f"  {profile.get('communication_address', '(address on file)')}")
    lines.append(f"  Attention: {profile.get('authorized_signatory_name', 'Authorised Signatory')}")
    lines.append("")
    lines.append(f"**Tender:** {tender_info['name']}")
    lines.append(f"**NIT No.:** {tender_info['nit_no']}")
    lines.append(f"**Estimated Contract Value:** ₹{tender_info['ecv_cr']:.2f} crore")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("Dear Sir/Madam,")
    lines.append("")
    lines.append(
        f"This is to acknowledge receipt of your bid submitted on **{bid_sub.get('submission_date', '?')}** "
        f"for the captioned tender. The following bid documents have been received and "
        f"recorded in the procurement portal:")
    lines.append("")
    lines.append("### Documents received")
    lines.append("")
    lines.append(f"1. **Letter of Bid** — signed by *{lob.get('signing_authority', profile.get('authorized_signatory_name', '?'))}*")
    lines.append(f"   - Bid amount: ₹{lob.get('bid_amount_cr', 0.0):.2f} crore")
    lines.append(f"   - Bid validity: {lob.get('bid_validity_days', 90)} days")
    lines.append("")
    lines.append(f"2. **Earnest Money Deposit (EMD) Bank Guarantee**")
    lines.append(f"   - Issuing bank: {emd.get('bg_issuing_bank', '?')}")
    lines.append(f"   - BG amount: ₹{emd.get('bg_amount_cr', 0.0):.2f} crore")
    lines.append(f"   - BG validity: {emd.get('bg_validity_days', 180)} days; unconditional: {emd.get('bg_unconditional', True)}")
    lines.append("")
    lines.append(f"3. **Priced Bill of Quantities (BoQ)**")
    lines.append(f"   - Total line items: {boq.get('line_item_count', '?')}")
    lines.append(f"   - Each page signed: {boq.get('each_page_signed', True)}")
    lines.append("")
    lines.append("### Next steps")
    lines.append("")
    lines.append(
        "Your bid will be evaluated by the Tender Scrutiny Committee per the timeline "
        "published in the NIT. You will receive a separate communication once evaluation "
        "completes (typically within 21 working days post-deadline closure). No further "
        "action is required from you at this stage.")
    lines.append("")
    lines.append(
        "If any discrepancy is observed between the documents listed above and the "
        "documents you actually submitted, please raise a written objection within "
        "**3 working days** of receipt of this acknowledgement.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("**Yours faithfully,**")
    lines.append("")
    lines.append("Procurement Authority")
    lines.append("(Communication generated by SYSTEM)")
    lines.append("")
    lines.append("**Drilldown reference:**")
    lines.append("")
    lines.append(f"- BidSubmission node_id: `{bid_sub.get('node_id')}`")
    lines.append(f"- LetterOfBid node_id: `{supps.get('LetterOfBid', {}).get('node_id')}`")
    lines.append(f"- EMD_BG node_id: `{supps.get('EMD_BG', {}).get('node_id')}`")
    lines.append(f"- PricedBoQ node_id: `{supps.get('PricedBoQ', {}).get('node_id')}`")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    print("=" * 76)
    print(f"  M4.5 Drafter — {COMMUNICATION_TYPE}")
    print("=" * 76)
    sentinel_pre = snapshot_sentinels()
    n_prior = delete_prior_communications(COMMUNICATION_TYPE, SOURCE_REF)
    if n_prior:
        print(f"  cleanup: deleted {n_prior} prior")

    bids = rest_get_range("kg_nodes", {
        "select": "node_id,doc_id,properties",
        "node_type": "eq.BidSubmission",
    })
    print(f"  {len(bids)} BidSubmissions to acknowledge")
    n_emitted = 0
    for bs in bids:
        bp = bs["properties"] or {}
        bidder_id = bp.get("bidder_profile_id")
        tender_id = bp.get("tender_id")
        doc_id = bs["doc_id"]
        if not (bidder_id and tender_id):
            continue
        profile = (get_bidder_profile(bidder_id) or {}).get("properties") or {}
        tinfo = get_tender_info(tender_id)
        supps = fetch_supplementaries_for_bid(doc_id)
        bid_sub = {"node_id": bs["node_id"],
                   "submission_date": bp.get("submission_date")}

        source_ids = [bs["node_id"]] + [v["node_id"] for v in supps.values()]
        audit_id = compute_audit_id(COMMUNICATION_TYPE, bidder_id, tender_id, source_ids)
        content_en = compose_content_en(profile, tinfo, bid_sub, supps)

        bidder_key = bidder_id.replace("bid_synth_profile_", "")
        tender_key = tender_id.replace("tender_synth_", "")
        artifact_path = ARTIFACT_DIR / f"{COMMUNICATION_TYPE}_{bidder_key}_{tender_key}.md"
        artifact_path.write_text(content_en, encoding="utf-8")

        comm_props = {
            "communication_type":          COMMUNICATION_TYPE,
            "recipient_bidder_profile_id": bidder_id,
            "recipient_email":             profile.get("email_primary"),
            "recipient_role":              None,
            "tender_id":                   tender_id,
            "sender_role":                 SENDER_ROLE,
            "channel":                     "EMAIL",
            "language":                    "EN",
            "status":                      "DRAFT",
            "audit_id":                    audit_id,
            "source_finding_node_ids":     source_ids,
            "content_en":                  content_en,
            "content_te":                  None,
            "artifact_path_md":            str(artifact_path),
            "artifact_path_docx":          None,
            "artifact_path_pdf":           None,
            "extracted_by":                SOURCE_REF,
            "defeated":                    False,
            "n_source_findings":           len(source_ids),
            "bidder_name":                 profile.get("company_name"),
            "tender_name":                 tinfo["name"],
            "tender_nit_no":               tinfo["nit_no"],
        }
        label = f"BID_ACK — {profile.get('company_name','?')[:40]} × {tinfo['name'][:30]}"
        rest_post("kg_nodes", [{
            "doc_id": tender_id, "node_type": "Communication",
            "label": label, "properties": comm_props, "source_ref": SOURCE_REF,
        }])
        n_emitted += 1
        print(f"  ✓ {bidder_key:8s} × {tender_key:8s}  audit={audit_id}")

    sentinel_post = snapshot_sentinels()
    assert_sentinel_preserved(sentinel_pre, sentinel_post)
    print(f"\n✓ {COMMUNICATION_TYPE}: {n_emitted} emitted; sentinel preserved")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
